/**
 * generate-config.js
 * Runs at Netlify build time (see netlify.toml).
 * Reads Firebase credentials from Netlify environment variables and writes
 * firebase-config.js so the app can connect to Firebase without committing
 * secrets to GitHub.
 *
 * Required Netlify env vars (set in Site → Environment variables):
 *   FIREBASE_API_KEY
 *   FIREBASE_AUTH_DOMAIN
 *   FIREBASE_PROJECT_ID
 *   FIREBASE_STORAGE_BUCKET
 *   FIREBASE_MESSAGING_SENDER_ID
 *   FIREBASE_APP_ID
 *   FIREBASE_MEASUREMENT_ID   (optional)
 */

const fs = require('fs');

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
];

const missing = required.filter((k) => !process.env[k]);
if (missing.length) {
  console.error('[generate-config] Missing environment variables:', missing.join(', '));
  console.error('Set them in Netlify → Site → Environment variables.');
  process.exit(1);
}

const config = `/**
 * Auto-generated by generate-config.js at build time.
 * Do NOT edit this file manually — it is overwritten on every deploy.
 */
export const firebaseConfig = {
  apiKey:            '${process.env.FIREBASE_API_KEY}',
  authDomain:        '${process.env.FIREBASE_AUTH_DOMAIN}',
  projectId:         '${process.env.FIREBASE_PROJECT_ID}',
  storageBucket:     '${process.env.FIREBASE_STORAGE_BUCKET}',
  messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID}',
  appId:             '${process.env.FIREBASE_APP_ID}',
  measurementId:     '${process.env.FIREBASE_MEASUREMENT_ID || ''}',
};
`;

fs.writeFileSync('firebase-config.js', config, 'utf8');
console.log('[generate-config] firebase-config.js written successfully.');
